sudo: required
dist: trusty
language: php

# versi PHP
php:
  - 7.1

#Branch yang digunakan

branches :
  only:
    - master #-> QA/Staging server
    - develop #-> DevServer


# build
before_script:
  - cp .env.travis .env
  - composer install --no-interaction
  - php artisan key:generate

# test
script :
  - ./vendor/bin/phpunit

#develoy
after_success :


