sudo: required
dist: trusty
language: php

# versi PHP
php:
  - 7.1

#Branch yang digunakan

branches :
  only:
    - master #-> QA/Staging server
    - develop #-> DevServer

#install enviroment di OS
before_install:
- curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
- chmod +x ./kubectl #permisions
- sudo mv ./kubectl/usr/local/bin/kubectl # Move to presisten
# Precompile
before_script:

# Hain Execution (Build)
script :


